version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: word_trainer_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: word_trainer
    ports:
      - "5432:5432"
    volumes:
      - word_trainer_data:/var/lib/postgresql/data
      - ./internal/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d word_trainer"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: word_trainer
      JWT_SECRET: supersecretkey
    ports:
      - "8080:8080"

volumes:
  word_trainer_data: